CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3._pet (id uuid, name text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "position" double precision, "searchVector" tsvector, species USER-DEFINED, traits ARRAY, comments text, age double precision, "locationAddressStreet1" text, "locationAddressStreet2" text, "locationAddressCity" text, "locationAddressPostcode" text, "locationAddressState" text, "locationAddressCountry" text, "locationAddressLat" numeric, "locationAddressLng" numeric, "vetPhonePrimaryPhoneNumber" text, "vetPhonePrimaryPhoneCountryCode" text, "vetPhonePrimaryPhoneCallingCode" text, "vetPhoneAdditionalPhones" jsonb, "vetEmailPrimaryEmail" text, "vetEmailAdditionalEmails" jsonb, birthday date, "isGoodWithKids" boolean, "picturesPrimaryLinkLabel" text, "picturesPrimaryLinkUrl" text, "picturesSecondaryLinks" jsonb, "averageCostOfKibblePerMonthAmountMicros" numeric, "averageCostOfKibblePerMonthCurrencyCode" text, "makesOwnerThinkOfFirstName" text, "makesOwnerThinkOfLastName" text, "soundSwag" USER-DEFINED, bio text, "interestingFacts" ARRAY, "extraData" jsonb);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."_surveyResult" (id uuid, name text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "position" double precision, "searchVector" tsvector, score double precision, "percentageOfCompletion" double precision, participants double precision, "averageEstimatedNumberOfAtomsInTheUniverse" double precision, comments text, "shortNotes" text);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."apiKey" (id uuid, name text, "expiresAt" timestamp with time zone, "revokedAt" timestamp with time zone, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.attachment (id uuid, name text, "fullPath" text, type text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "authorId" uuid, "taskId" uuid, "noteId" uuid, "personId" uuid, "companyId" uuid, "opportunityId" uuid, "petId" uuid, "surveyResultId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."auditLog" (id uuid, name text, properties jsonb, context jsonb, "objectName" text, "objectMetadataId" text, "recordId" uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workspaceMemberId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.blocklist (id uuid, handle text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workspaceMemberId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."calendarChannel" (id uuid, handle text, "syncStatus" USER-DEFINED, "syncStage" USER-DEFINED, visibility USER-DEFINED, "isContactAutoCreationEnabled" boolean, "contactAutoCreationPolicy" USER-DEFINED, "isSyncEnabled" boolean, "syncCursor" text, "syncedAt" timestamp with time zone, "syncStageStartedAt" timestamp with time zone, "throttleFailureCount" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "connectedAccountId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."calendarChannelEventAssociation" (id uuid, "eventExternalId" text, "recurringEventExternalId" text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "calendarChannelId" uuid, "calendarEventId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."calendarEvent" (id uuid, title text, "isCanceled" boolean, "isFullDay" boolean, "startsAt" timestamp with time zone, "endsAt" timestamp with time zone, "externalCreatedAt" timestamp with time zone, "externalUpdatedAt" timestamp with time zone, description text, location text, "iCalUID" text, "conferenceSolution" text, "conferenceLinkPrimaryLinkLabel" text, "conferenceLinkPrimaryLinkUrl" text, "conferenceLinkSecondaryLinks" jsonb, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."calendarEventParticipant" (id uuid, handle text, "displayName" text, "isOrganizer" boolean, "responseStatus" USER-DEFINED, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "calendarEventId" uuid, "personId" uuid, "workspaceMemberId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.company (id uuid, name text, "domainNamePrimaryLinkLabel" text, "domainNamePrimaryLinkUrl" text, "domainNameSecondaryLinks" jsonb, employees double precision, "linkedinLinkPrimaryLinkLabel" text, "linkedinLinkPrimaryLinkUrl" text, "linkedinLinkSecondaryLinks" jsonb, "xLinkPrimaryLinkLabel" text, "xLinkPrimaryLinkUrl" text, "xLinkSecondaryLinks" jsonb, "annualRecurringRevenueAmountMicros" numeric, "annualRecurringRevenueCurrencyCode" text, "addressAddressStreet1" text, "addressAddressStreet2" text, "addressAddressCity" text, "addressAddressPostcode" text, "addressAddressState" text, "addressAddressCountry" text, "addressAddressLat" numeric, "addressAddressLng" numeric, "idealCustomerProfile" boolean, "position" double precision, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "accountOwnerId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."connectedAccount" (id uuid, handle text, provider text, "accessToken" text, "refreshToken" text, "lastSyncHistoryId" text, "authFailedAt" timestamp with time zone, "handleAliases" text, scopes ARRAY, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "accountOwnerId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.favorite (id uuid, "position" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workspaceMemberId" uuid, "personId" uuid, "companyId" uuid, "favoriteFolderId" uuid, "opportunityId" uuid, "workflowId" uuid, "workflowVersionId" uuid, "workflowRunId" uuid, "taskId" uuid, "noteId" uuid, "viewId" uuid, "petId" uuid, "surveyResultId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."favoriteFolder" (id uuid, "position" double precision, name text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.message (id uuid, "headerMessageId" text, subject text, text text, "receivedAt" timestamp with time zone, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "messageThreadId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."messageChannel" (id uuid, visibility USER-DEFINED, handle text, type USER-DEFINED, "isContactAutoCreationEnabled" boolean, "contactAutoCreationPolicy" USER-DEFINED, "excludeNonProfessionalEmails" boolean, "excludeGroupEmails" boolean, "isSyncEnabled" boolean, "syncCursor" text, "syncedAt" timestamp with time zone, "syncStatus" USER-DEFINED, "syncStage" USER-DEFINED, "syncStageStartedAt" timestamp with time zone, "throttleFailureCount" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "connectedAccountId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."messageChannelMessageAssociation" (id uuid, "messageExternalId" text, "messageThreadExternalId" text, direction USER-DEFINED, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "messageChannelId" uuid, "messageId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."messageFolder" (id uuid, name text, "syncCursor" text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "messageChannelId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."messageParticipant" (id uuid, role USER-DEFINED, handle text, "displayName" text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "messageId" uuid, "personId" uuid, "workspaceMemberId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."messageThread" (id uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.note (id uuid, "position" double precision, title text, "bodyV2Blocknote" text, "bodyV2Markdown" text, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."noteTarget" (id uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "noteId" uuid, "personId" uuid, "companyId" uuid, "opportunityId" uuid, "petId" uuid, "surveyResultId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.opportunity (id uuid, name text, "amountAmountMicros" numeric, "amountCurrencyCode" text, "closeDate" timestamp with time zone, stage USER-DEFINED, "position" double precision, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "pointOfContactId" uuid, "companyId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.person (id uuid, "nameFirstName" text, "nameLastName" text, "emailsPrimaryEmail" text, "emailsAdditionalEmails" jsonb, "linkedinLinkPrimaryLinkLabel" text, "linkedinLinkPrimaryLinkUrl" text, "linkedinLinkSecondaryLinks" jsonb, "xLinkPrimaryLinkLabel" text, "xLinkPrimaryLinkUrl" text, "xLinkSecondaryLinks" jsonb, "jobTitle" text, "phonesPrimaryPhoneNumber" text, "phonesPrimaryPhoneCountryCode" text, "phonesPrimaryPhoneCallingCode" text, "phonesAdditionalPhones" jsonb, city text, "avatarUrl" text, "position" double precision, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "companyId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.task (id uuid, "position" double precision, title text, "bodyV2Blocknote" text, "bodyV2Markdown" text, "dueAt" timestamp with time zone, status USER-DEFINED, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "assigneeId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."taskTarget" (id uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "taskId" uuid, "personId" uuid, "companyId" uuid, "opportunityId" uuid, "petId" uuid, "surveyResultId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."timelineActivity" (id uuid, "happensAt" timestamp with time zone, name text, properties jsonb, "linkedRecordCachedName" text, "linkedRecordId" uuid, "linkedObjectMetadataId" uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workspaceMemberId" uuid, "personId" uuid, "companyId" uuid, "opportunityId" uuid, "noteId" uuid, "taskId" uuid, "workflowId" uuid, "workflowVersionId" uuid, "workflowRunId" uuid, "petId" uuid, "surveyResultId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.view (id uuid, name text, "objectMetadataId" uuid, type text, key USER-DEFINED, icon text, "kanbanFieldMetadataId" text, "position" double precision, "isCompact" boolean, "kanbanAggregateOperation" USER-DEFINED, "kanbanAggregateOperationFieldMetadataId" uuid, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."viewField" (id uuid, "fieldMetadataId" uuid, "isVisible" boolean, size double precision, "position" double precision, "aggregateOperation" USER-DEFINED, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "viewId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."viewFilter" (id uuid, "fieldMetadataId" uuid, operand text, value text, "displayValue" text, "viewFilterGroupId" uuid, "positionInViewFilterGroup" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "viewId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."viewFilterGroup" (id uuid, "parentViewFilterGroupId" uuid, "logicalOperator" USER-DEFINED, "positionInViewFilterGroup" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "viewId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."viewGroup" (id uuid, "fieldMetadataId" uuid, "isVisible" boolean, "fieldValue" text, "position" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "viewId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."viewSort" (id uuid, "fieldMetadataId" uuid, direction text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "viewId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.webhook (id uuid, "targetUrl" text, operations ARRAY, description text, secret text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3.workflow (id uuid, name text, "lastPublishedVersionId" text, statuses ARRAY, "position" double precision, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."workflowEventListener" (id uuid, "eventName" text, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workflowId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."workflowRun" (id uuid, name text, "startedAt" timestamp with time zone, "endedAt" timestamp with time zone, status USER-DEFINED, "createdBySource" USER-DEFINED, "createdByWorkspaceMemberId" uuid, "createdByName" text, "createdByContext" jsonb, output jsonb, context jsonb, "position" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workflowVersionId" uuid, "workflowId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."workflowVersion" (id uuid, name text, trigger jsonb, steps jsonb, status USER-DEFINED, "position" double precision, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone, "workflowId" uuid);

CREATE TABLE workspace_3ixj3i1a5avy16ptijtb3lae3."workspaceMember" (id uuid, "nameFirstName" text, "nameLastName" text, "colorScheme" text, locale text, "avatarUrl" text, "userEmail" text, "userId" uuid, "timeZone" text, "dateFormat" USER-DEFINED, "timeFormat" USER-DEFINED, "searchVector" tsvector, "createdAt" timestamp with time zone, "updatedAt" timestamp with time zone, "deletedAt" timestamp with time zone);